mysql:
  dns: root:00000.@tcp(127.0.0.1:3306)/booklibrary?charset=utf8mb4&parseTime=True&loc=Local
# redis:
#   addr: "127.0.0.1:6379"
#   password: ""
#   DB: 0
#   poolSize: 30
#   minIdleConn: 30
# oss:
#   Endpoint: "oss-cn-hangzhou.aliyuncs.com"
#   AccessKeyId: "LTAI5tNCXPJwS3MstKoKgixh"
#   AccessKeySecret: "YhHE8OyCMsqfjwOnxQ1oO7paYlDjVHX"
#   Bucket : "ginchat"

# timeout:
#   DelayHeartbeat: 3   #延迟心跳时间  单位秒
#   HeartbeatHz: 30   #每隔多少秒心跳时间   
#   HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
#   RedisOnlineTime: 4  #缓存的在线用户时长   单位H

# port:
#   server: ":8080"
#   udp: 3001
